// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJTH29kMY479SogKQh3fQUJzPgUvub1PY',
    appId: '1:607915335501:android:130b08d867ea5382132104',
    messagingSenderId: '607915335501',
    projectId: 'blue-sailing-test-8a843',
    databaseURL: 'https://blue-sailing-test-8a843-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'blue-sailing-test-8a843.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChcH2OudJgOuKD7zGR8IYAqOKLbXqxWJk',
    appId: '1:607915335501:ios:3cd52ffb7129e06a132104',
    messagingSenderId: '607915335501',
    projectId: 'blue-sailing-test-8a843',
    databaseURL: 'https://blue-sailing-test-8a843-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'blue-sailing-test-8a843.firebasestorage.app',
    iosBundleId: 'com.app.app',
  );
}
