import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'theme/app_theme.dart';
import 'screens/auth/email_verification_screen.dart';
import 'screens/auth/login_screen.dart';
import 'screens/home/home_screen.dart';
// Generated by FlutterFire CLI — add your own firebase_options.dart
import 'firebase_options.dart';
import 'services/auth_service.dart';
import 'package:flutter/widgets.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (Firebase.apps.isEmpty) {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }

  runApp(const BlueSailingApp());
}
  class BlueSailingApp extends StatefulWidget {
    const BlueSailingApp({super.key});

    @override
    State<BlueSailingApp> createState() => _BlueSailingAppState();
  }

  class _BlueSailingAppState extends State<BlueSailingApp> with WidgetsBindingObserver {
    final AuthService _authService = AuthService();

    @override
    void initState() {
      super.initState();
      WidgetsBinding.instance.addObserver(this);
    }

    @override
    void dispose() {
      WidgetsBinding.instance.removeObserver(this);
      super.dispose();
    }

    @override
    void didChangeAppLifecycleState(AppLifecycleState state) {
      // When app is backgrounded or detached, sign out to ensure session expires on exit.
      if (state == AppLifecycleState.paused || state == AppLifecycleState.detached) {
        _authService.signOut();
      }
    }

    @override
    Widget build(BuildContext context) {
      return MaterialApp(
        title: 'Blue Sailing Tests',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.theme,
        home: const _AuthGate(),
      );
    }
  }

/// Routes to HomeScreen if signed in, LoginScreen if not.
class _AuthGate extends StatelessWidget {
  const _AuthGate();

  

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(color: AppTheme.gold),
            ),
          );
        }
        if (snapshot.hasData && snapshot.data != null) {
          final user = snapshot.data!;
          if (!user.emailVerified) {
            return const EmailVerificationScreen();
          }
          return const HomeScreen();
        }
        return const LoginScreen();
      },
    );
  }
}
